### ISSUE TITLE
Propagate build status

### ISSUE THREAD

**Issue by marcus-bcl** [dark-mechanicum/aws-codebuild#38]
Hello, it would be great if this GitHub Action failed whenever the CodeBuild project failed (or timed out, or was cancelled).  Similar to how the AWS action works: https://github.com/aws-actions/aws-codebuild-run-build/blob/95cc38b1d458ebdba0f5eeb8a61d1f797e9b2599/index.js#L21-L25

At the moment, this action will always succeed - which doesn't give any indication of build issues or test failures.

**Comment by akazakou** [comment]
@marcus-bcl great idea! I will add this at the current weekend :) 

FYI: Already implemented behavior for canceling jobs from GitHub Actions. If you'll click the "Cancel Workflow" button in the GitHub Actions interface - it will automatically cancel assiciated AWS CodeBuild job

**Comment by akazakou** [comment]
@marcus-bcl Hi! I've published new version of GitHub Action with requested feature that was implemented in #43 
Please, verify it and tell me how it works :)

**Comment by marcus-bcl** [comment]
Awesome, thank you!
