### ISSUE TITLE
Action hangs after codebuild finishes

### ISSUE THREAD

**Issue by henderjm** [dark-mechanicum/aws-codebuild#96]
Hi,

I have a github matrix setup for building multiple applications in a monolith repo at once. I have noticed that even though Codebuild has finished its job that the github action continues to hang. It should take no longer than 5minutes to build from a cold self hosted runner startup.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1973141/202921477-bf40191c-cba7-4d21-8a1d-e783808485a5.png">

I can't see the logs during the run but when I cancel the workflow I can see all the logs that should have completed the github action.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1973141/202921582-dc5b82dd-d82a-4f89-ad73-aef76f3d6c3c.png">

Perhaps there is something I can do in our buildspec to help?

Any suggestion welcome.

**Comment by akazakou** [comment]
Hi @henderjm ,

Please provide a configuration for your job run and re-run the job in Debug mode, to get additional logs. 

![How to re-run job in debug mode](https://user-images.githubusercontent.com/326397/180428925-bc29e7b3-debc-4a93-9a8f-94530b9b1a4e.png)

**Comment by akazakou** [comment]
It was closed due to not respond the topic starter.
